title: My nice new blog
author: Chris Gerrard
email: Chris@Gerrard.net
description: > # this means to ignore newlines until "baseurl:"
  This is a truly innovatieve and awesome Jekyll site.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
